require:
  - rubocop-katalyst

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    # Dummy app
    - spec/dummy/*
    - spec/dummy/bin/*
    - spec/dummy/config/**/*
    - spec/dummy/db/**/*
    - spec/dummy/deploy/*
    - spec/dummy/node_modules/**/*
    - spec/dummy/vendor/bundle/**/*
